//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodSharingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.PostOrders = new HashSet<PostOrder>();
        }
    
        public int PostID { get; set; }
        public int UserID { get; set; }
        public string PostTitle { get; set; }
        public string PostDescription { get; set; }
        public byte[] PostImage { get; set; }
        public string PostLocation { get; set; }
        public System.DateTime PostDate { get; set; }
        public System.DateTime FoodExpirationDate { get; set; }
        public string DietaryInformation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostOrder> PostOrders { get; set; }
        public virtual User User { get; set; }
    }
}
