//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodSharingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostOrder
    {
        public int PostOrderID { get; set; }
        public int PostID { get; set; }
        public System.DateTime PostOrderDate { get; set; }
        public string PostOrderStatus { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
