//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodSharingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestOrder
    {
        public int RequestOrderID { get; set; }
        public int RequestID { get; set; }
        public System.DateTime RequestOrderDate { get; set; }
        public string RequestOrderStatus { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
