//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodSharingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.RequestOrders = new HashSet<RequestOrder>();
        }
    
        public int RequestID { get; set; }
        public int UserID { get; set; }
        public string RequestTitle { get; set; }
        public string RequestDescription { get; set; }
        public byte[] RequestImage { get; set; }
        public string RequestLocation { get; set; }
        public System.DateTime RequestDate { get; set; }
        public System.DateTime FoodExpirationDate { get; set; }
        public string AllergenInformation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestOrder> RequestOrders { get; set; }
        public virtual User User { get; set; }
    }
}
